### ISSUE TITLE
Reconnect: multiple reconnects fail

### ISSUE THREAD

**Issue by benjamin-dk** [cfdp/opeka#127]
When a regular user (non-admin) loses connection the first time, the connection is reestablished as it should.

But if the user loses connection again during the same session, the reconnect fails and the user is presented with the "Lost connection to server" window.

This error relates to #94 

```
newState for 96505cfe-190e-46a0-af64-ac160da8ca5d is:  1
newState for e95387a9-9c69-4c30-8779-78c9ad8b3afb is:  3
could not close connection for clientId = e95387a9-9c69-4c30-8779-78c9ad8b3afb - self.server undefined.
Connection 1776528 released
Client disconnected: sinceTimeout > disconnectLimit for 90c5b943-ca9a-4686-be7e-d4a28bc8f916
newState for 90c5b943-ca9a-4686-be7e-d4a28bc8f916 is:  3
could not close connection for clientId = 90c5b943-ca9a-4686-be7e-d4a28bc8f916 - self.server undefined.
Client disconnected: onConnectionClosed e95387a9-9c69-4c30-8779-78c9ad8b3afb
newState for e95387a9-9c69-4c30-8779-78c9ad8b3afb is:  2
Client disconnected: sinceTimeout > disconnectLimit for e95387a9-9c69-4c30-8779-78c9ad8b3afb
newState for e95387a9-9c69-4c30-8779-78c9ad8b3afb is:  3
could not close connection for clientId = e95387a9-9c69-4c30-8779-78c9ad8b3afb - self.server undefined.
latency > disconnectLimit: Time to disconnect user  96505cfe-190e-46a0-af64-ac160da8ca5d
newState for 96505cfe-190e-46a0-af64-ac160da8ca5d is:  2
Client disconnected: sinceTimeout > disconnectLimit for 96505cfe-190e-46a0-af64-ac160da8ca5d
2018-03-20T10:42:04.058Z - info: removeUserFromRoom, clientId: undefined , admin?  undefined
2018-03-20T10:42:04.058Z - warning: ChatStartMin not defined, statistics not saved!
newState for 96505cfe-190e-46a0-af64-ac160da8ca5d is:  3
2018-03-20T10:42:04.072Z - info: Regular user disconnected. 96505cfe-190e-46a0-af64-ac160da8ca5d 196
2018-03-20T10:42:04.073Z - info: Disconnected user had activeRoomId:  67281416-c1cc-4203-8fbe-870f164bb984
2018-03-20T10:42:04.073Z - info: removeUserFromRoom, clientId: 96505cfe-190e-46a0-af64-ac160da8ca5d , admin?  undefined
2018-03-20T10:42:04.073Z - info: User left room: Chat duration (minutes):  13
Connection 1776527 acquired
Connection 1776527 released
Connection 1776526 acquired
20 Mar 10:42:04 - Info: Saved chat duration into stats.
Connection 1776526 released
```

**Comment by jubk** [comment]
This is probably an issue with disconnectLimit (or client.connectionData.disconnectLimit) being null due to it not being defined in the server configuration file, which causes the server to always switch the user to state 3 (DISCONNECTED) if client.checkDisconnect is called before the client can reconnect.

This issue should probably be solved by figuring out exactly how timeout values should be configured and how they should be handled on both client and server side.

It would make sense to use the values stored in the "opeka_reconnect_attempts" and "opeka_reconnect_interval" settings from Drupal. To avoid querying the database each time the server need to check a timeout these values could be looked up every time a client connects and then cached on the server until the next client connects.

I would suggest the following setup, which can be done with the current Drupal-editable configuration values:

"opeka_reconnect_interval" is renamed (in the user interface) to something like "connection timeout/reconnect interval". If either end of the connection experiences that no communication has happened within this interval they will change the connection state to "PENDING_TIMEOUT(server)/TRYING_RECONNECT(client)".
When this happens the client will immediatly spawn a try-to-reconnect connection and keep spawning such connections every "opeka_reconnect_interval" until either the connection is restored or "opeka_reconnect_attempts" is exceeded. If "opeka_reconnect_attempts" is exceeded the client will switch state to DISCONNECTED and show the "Lost connection to server" message to the user.
When a server has a client in the PENDING_TIMEOUT state it will match the time since last communication with the client against the disconnectLimit and register the client as disconnected if this limit is exceeded. To allow clients the time to perform all the configured reconnect attemps disconnectLimit is calculated as (opeka_reconnect_interval * (opeka_reconnect_attempts + 1))
There is one more value that needs to be taken into account and that is how often the server should ping the clients. I suggest that this should be done with an interval of half the value of opeka_reconnect_interval, so there is plenty of time for a reply to arrive.

/jubk
