### ISSUE TITLE
Scroll-bar not properly draggable with "Pause auto-scroll" enabled

### ISSUE THREAD

**Issue by cfdp** [cfdp/opeka#71]
The scrollbar can only be dragged a small distance before you need to "regrab" it and drag it again.

This means it takes a long time to scroll through a long conversation

To recreate the issue, open a chat room, make sure the "Pause auto-scroll" is enabled and post a good number of messages.

Experienced on Firefox, Mac OS.

**Comment by alex-bukach** [comment]
@benjamin-dk try to drag scroller with "Pause auto-scroll" *disabled*, don't you experience the same issue? I do.

**Comment by alex-bukach** [comment]
In fact I'd say not "small distance", but "small time".

**Comment by alex-bukach** [comment]
@benjamin-dk it happens since whole chat window is completely replaced with the new one (i.e. re-rendered) after each socket request (which are sent frequently) and on received message. The proposed solution (see https://github.com/cfdp/opeka/pull/72) is to pause updating the window until scrolling is stopped.

**Comment by cfdp** [comment]
@alex-bukach you're right, the issue is also present without having the feature enabled.

Your solution seems to work nicely, thx!
